q=input("Введите первое число")
w=input("Введите второе число")
e=input("Введите третье число")
q=int(q)
w=int(w)
e=int(e)
print ("Cумма введеных чисел")
r=(q+w+e)
print (r)
t=(q*w*e)
print("Произведение введеных чисел")
print(t)